export const UPDATE_AUTH = 'UPDATE_AUTH';
export const UPDATE_LOGIN_USERID = "UPDATE_LOGIN_USERID"
export const UPDATE_LOGIN_PASSWORD = "UPDATE_LOGIN_PASSWORD"
export const UPDATE_LOGIN_ROLE = "UPDATE_LOGIN_ROLE"
export const UPDATE_LOGIN_NICKNAME = "UPDATE_LOGIN_NICKNAME"
export const UPDATE_LOGIN_PROFILE_IMG = "UPDATE_LOGIN_PROFILE_IMG"
export const UPDATE_LOGGED_IN = "UPDATE_LOGGED_IN"
export const UPDATE_LOGIN_USERPK = "UPDATE_LOGIN_USERPK"